[package]
name = "reldate"
version = "0.1.0"
authors = ["Diwaker Ghimire <idwaker@gmail.com>"]

[lib]
name = "datestream"
src = "src/datestream.rs"

[dependencies]

chrono = "*"
#rustc-searilize = "*"

[dependencies.clap]

git = "https://github.com/kbknapp/clap-rs.git"